### ISSUE TITLE
A9X not supported

### ISSUE THREAD

**Issue by ak99004242** [0x7ff/eclipsa#7]
A9X doesn’t work. Can u please add that. Thanks

**Comment by 0x7ff** [comment]
Sorry, it's not possible to support this device as the controller_task leak has been fixed on A9X and later (you can see task_destroy (0x10000A05C) is called inside synopsys_otg_stop (0x100005130)). However, since checkra1n supports this device, you can boot the raw image with "bootr" command using PongoOS.

**Comment by ak99004242** [comment]
> Sorry, it's not possible to support this device as the controller_task leak has been fixed on A9X and later (you can see task_destroy (0x10000A05C) is called inside synopsys_otg_stop (0x100005130)). However, since checkra1n supports this device, you can boot the raw image with "bootr" command using PongoOS.

I have already tried that. I can load ibec but no matter which version of iOS I use I can’t use go command. I have also tried sending iboot.img4 but still no luck. The problem is I can’t load raw ibss from pongo. I have already patched the files etc. I also replicated the same thing on A9 to check if it works but it doesn’t. So it seems like unless ibss is loaded first only then ibec can be loaded properly. Please let me know if u have a solution for this or ipwndfu for A9x (s8001) or will there be non?
